server:
  port: 8083

spring:
  application:
    name: apigateway

zuul:
#  prefix: /api/v1
  routes:
    commondservice:
      path: /command/**
      serviceId: commondservice
    queryservice:
      path: /query/**
      serviceId: queryservice
 

#ribbon:
#  eureka:
#    enabled: true    

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/