server:
  port: 8083

spring:
  application:
    name: apigateway

zuul:
  prefix: /api/v1
  routes:
    commondservice:
      path: /command/**
      serviceId: commandservice
    queryservice:
      path: /query/**
      serviceId: queryservice
 

#ribbon:
#   readTimeout: 5000
#   connection-timeout: 3000
#   eureka:
#      enabled: true
#      
#hystrix:
#  commandservice:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 40000   
            
      

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30