spring:
  profiles: default
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: queryservice
  kafka:
    listener:
      missing-topics-fatal: false
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
        mongodb:
            database: stock_market_query
            host: localhost
            port: 27017
#            uri: mongodb://localhost:27017/stock_market_query?maxpoolsize=5
            repositories:              type: auto
            
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/stock_market?createDatabaseIfNotExist=true
#    username: stock
#    password: stock123
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: dd-MM-yyyy
    time-zone: Asia/Kolkata
server:
  port : 8082
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true    lease-renewal-interval-in-seconds: 30
  
---
spring:
  profiles: docker
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: queryservice
  kafka:
    listener:
      missing-topics-fatal: false
    consumer:
      bootstrap-servers: kafka:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#  data:
#    mongodb:
#      uri: mongodb://mongo_db:27017/stock_market
  data:
    mongodb:
      database: stock_market
      host: mymongodb
      port: 27017
  jackson:
    date-format: dd-MM-yyyy
    time-zone: Asia/Kolkata      
server:
  port : 8082
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://sm-registry:8761/eureka/
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
