spring:
  profiles: default
  application:
    name: serviceregistry
eureka:
  client:
    registerWithEureka: false  
    fetchRegistry: false 
server:
  port : 8761
  
---
  
spring:
  profiles: docker
  application:
    name: serviceregistry
eureka:
  client:
    registerWithEureka: false  
    fetchRegistry: false 
server:
  port : 8761