server:
  port: 9191
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/auth?createDatabaseIfNotExist=true
    username: stock
    password: stock123
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  output:
    ansi:
      enabled: DETECT   
logging:
  level:
    org:
      hibernate:
        type: trace
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
          