spring:
  application:
    name: commandservice
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://localhost:3306/stock_market?createDatabaseIfNotExist=true
    username: stock
    password: stock123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: dd-MM-yyyy
    time-zone: Asia/Kolkata
server:
  port : 8082

