spring:
  profiles: default
  application:
    name: commandservice
  kafka:
    template:
      default-topic: stock_market
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://localhost:3306/stock_market?createDatabaseIfNotExist=true
    username: stock
    password: stock123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: dd-MM-yyyy
    time-zone: Asia/Kolkata
server:
  port : 8081
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
  
#commandservice:
#  ribbon:
#    listOfServers: http://localhost:8000, http://localhost:8001  

---
spring:
  profiles: docker
  application:
    name: commandservice
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://mysqldb:3306/stock_market?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: stock
    password: stock123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: dd-MM-yyyy
    time-zone: Asia/Kolkata
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://sm-registry:8761/eureka/
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
 
server:
  port: 8081