spring:
  application:
    name: commandservice
  kafka:
    template:
      default-topic: stock_market
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://localhost:3306/stock_market?createDatabaseIfNotExist=true
    username: stock
    password: stock123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: dd-MM-yyyy
    time-zone: Asia/Kolkata
server:
  port : 8081
